---
output:
  pdf_document: default
  html_document: default
---
# Requirements
<!-- 
An idea of what is required to make the project actually happen
-->

#### People

This work will be completed by the team at Why R foundation, some of whom are already actively working on the project.
The existing personnel will be complemented by the Funded Presenters.

<!--
Who needs to be involved, what's the proposed structure, what will it take to get their involvement?
-->

#### Processes
The Why R? foundation have a Code of Conduct that is accessible on the Why R? website. 
This Code of Conduct is updated on an ongoing basis. 
Additionally, a Code of Conduct specific to this project will be implemented.This Code of Conduct will align with COCs for similarly structured projects in the R community. 

We anticipate having meetings every 2 months about progress and quarterly ISC meetings.

<!-- 
What processes need to be put in place e.g. codes of conduct, regular ISC meetings, handover to the community at large?
-->

## Payments

Payments will be processed by the Why R? Foundation, but can be processed by the R consortium if preferable.
Payments will be made on the basis of professional services. Presenters are responsible for their own tax affairs. 
Payments will be made to each presenter and travel expenses will not be funded.

<!--
What is going to be needed to deliver this project? 

Will cloud computing be used - if yes are there are necessary components that will be deciding factors between providers?

Are there tools or tech that don't exist that will be produced to facilitate the project?
-->

## Funding

The Budget for this proposal is tabulated below. Both budget items are labour costs.


Item                                              | Cost (Euro)
------------------------------------------------- | ------------- 
Component 1 Stipends (30 webinars)  |  5,100  
Component 2 Stipends (40 videos)  |  3,200
------------------------------------------------- | ------------- 
Total                                             |  8,300



<!-- 
[TO DO] THE GUIDANCE IS PRETTY UNCLEAR, ESP IN LIGHT OF GABOR'S PROPOSAL VS AWARD SIZE

-->

<!--  ## Summary -->


<!--
A summary of the requirements that contextualises the costs
-->
