# Signatories
<!-- 
This section provides the ISC with a view of the support received from the community for a proposal. Acceptance isn't predicated on popularity but community acceptance is important.  Willingness to accept outside input is also a good marker for project delivery. 

An optional section would be for R-Core signatories where changes to R are proposed.
-->

The applicant is the Why R? Foundation, which is incorporated under Polish law. (More details can be found at the Why R? website: www.whyr.pl) 

<!-- 
The postal address is 

FUNDACJA WHY R? / WHY R? Foundation
ul. Krasnobrodzka 2/190, 
03-214 Warszawa, 
Poland
-->

The Why R? Foundation management board is 

* Marcin Piotr Kosinski (chair),
* Bartosz Sakiewicz (vice-chair),
* Agnieszka Borsuk-De Moor (vice-chair),
* Michal Jan Burdukiewicz (amanuensis).

## Seminar Series Project team
* Marcin Kosinski (Project Leader)
* Michal Burdukiewicz (Project Officer)
* Kevin O'Brien (Project Officer)
* Lais Carvalho (Presenter & Research)
* Ahmadou Dicko (Presenter & Research)

<!-- 
Who are the people responsible for actually delivering the project if the proposal gets accepted and are already signed up and rearing to go?
-->

## Consulted

* [gwynn sturdevant](https://www.nzgwynn.com/), RForwards member, RConsortium DI-WG member, RLadies DC organizer, useR! 2020 Diversity committee 
* [Lais Carvalho](https://www.laiscarvalho.com/), Member of Python Ireland, Volunteer at PyjamasConf and EuroPython
* Joseph Rickert, Chair of the R Consortium.
* Additionally please note the many R commununity members who have given webinars since April 2020.

<!-- 
* Ola Petrykiewicz (Why R? Foundation Marketing Expert)
* Olgun Aydin (Why R? Foundation Sponsorship Coordinator)
* Michal Maj (Why R? Foundation Community Manager)
* Emil Buszyo (Why R? Foundation Web Designer)
-->




<!-- 
Who has been given the opportunity to provide feedback on the proposal? This should include any R Consortium & ISC members who the proposal has been discussed with.
-->

