# Success
<!-- 
Projects should have a definition of done that is measurable, and a thorough understanding going in of what the risks are to delivery 
-->

## Definition of Success

We define success as successful continuation of the Why R? webinar series, with contributions from R users from a broad diversity of specicialities, backgrounds and geographic locations. Additionally we foresee stronger relationships with corporate partners, and enter into sponsorship agreements. This will sustain Why R? foundations ability to provide financial support to the broader R community.
<!-- 
What does success look like? 
-->

## Measuring success
In the first instance, Success would be defined as the completion of agreed number of webinars, with each webinar receiving 500 views on average within 28 days of the initial livestream.

We will measure this by the outputs that we have made freely available to the R Community. We will summarize information and make it available to all.

<!-- 
How will we know when success is achieved, what markers can we use along the way 
-->

## Future work
It is our ambition to have a parallel series of webinars for Asia and Oceania. This series would highlight the contribution of the R community in that part of the world. The webinars would need to take place at an appropriate time (e.g. 11am UTC). We hope to recruit presenters from the region. We would also need to appoint and train webinar producers who will be available at appropriate times.

Why R? notes the strong eco-system of the R communities in the American continents. Why R? will seek to support the growth of these communities, and will be available for future collaborations. For the foreseeable future, the Why R? foundation does not plan run R community events, unless in partnership with a local entity. This does not preclude people from the Americas participating in our current pattern of events (i.e. events scheduled for European and African time zones)



<!-- 
How could this be extended / developed in the future by yourself and/or the community in general?
-->

## Key risks

We are hopeful that we can continue to find high quality speakers from a broad diversity of specicialities, backgrounds and geographic locations, who have the time to work with us.

<!-- 
What sort of things could come up that can delay or break the project?

 - [ ] People
 - [ ] Processes
 - [ ] Tooling & Technology
 - [ ] Costs

-->
